#!/usr/bin/bash
docker buildx build . --platform linux/arm64 -t hippo-release-builder
docker run --rm -it --platform linux/arm64 --ulimit nofile=2048:4096 -v ./debs:/debs hippo-release-builder:latest "$@"
